# version: "3.8"

services:
  nginx:
    build: nginx/.
    image: inception_nginx
    container_name: nginx
    ports:
      - "443:443"
      - "80:80"
    # restart: always
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - ../web:/var/www/html
    networks:
      - inception

  wordpress:
    build: wordpress/.
    image: inception_wordpress
    container_name: wp-php
    restart: always
    depends_on:
      - mariadb
#     environment:
#       - WORDPRESS_DB_HOST=mariadb
#       - WORDPRESS_DB_NAME=wordpress
#       - WORDPRESS_DB_USER=wpuser
#       - WORDPRESS_DB_PASSWORD=password
    volumes:
      - ../web:/var/www/html
    networks:
      - inception

  mariadb:
    build: mariadb/.
    image: inception_mariadb
    container_name: mariadb
#     restart: always
#     environment:
#       - MYSQL_ROOT_PASSWORD=rootpassword
#       - MYSQL_DATABASE=wordpress
#       - MYSQL_USER=wpuser
#       - MYSQL_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data: