services:
  nginx:
    build: nginx/.
    image: inception_nginx
    container_name: nginx
    ports:
      - "443:443"
    restart: always
    depends_on:
      - wordpress
      - mariadb
    volumes:
      - ../web:/var/www/html
    networks:
      - inception

  wordpress:
    build: wordpress/.
    image: inception_wordpress
    container_name: wp-php
    restart: always
    depends_on:
      mariadb:
        condition: service_healthy
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - WP_ADMIN_USER=${WP_ADMIN_USER}
      - WP_ADMIN_PASSWORD=${WP_ADMIN_PASSWORD}
      - WP_ADMIN_EMAIL=${WP_ADMIN_EMAIL}
      - WP_TITLE=${WP_TITLE}
      - WP_URL=${WP_URL}
    volumes:
      - ../web:/var/www/html
    networks:
      - inception

  mariadb:
    build: mariadb/.
    image: inception_mariadb
    container_name: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ../db:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", root, "-p${MYSQL_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../web
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ../db

networks:
  inception:
    driver: bridge