version: "3.8"

services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "4222:80"
    volumes:
      - ./web:/var/www/html
      # mount the web directory to the nginx container

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    volumes:
      - ./web:/var/www/html
      # mount the web directory to the wordpress container


